### ISSUE TITLE
Scanning of OnPush job is Unstable

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#160] opened 2021-06-17 18:31 UTC
Steps:
1. git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2. zebrunner setup
3. git pull --recurse-submodules
4. zebrunner restart
5. Register organization "okamara" 
6. Register repository
Actual result: Scanning of OnPush job completed in "Unstable" status
<img width="950" alt="Снимок экрана 2021-06-17 в 21 26 51" src="https://user-images.githubusercontent.com/32964663/122453688-3f1ea280-cfb3-11eb-84a1-6a462c2a7b32.png">

**Comment by vdelendik** [comment] 2021-06-18 07:50
root cause: absence of the active choice plugin and scripts approval.
it should be fixed in scope of #143. Testing details better to find in #143 as well

**Closed by vdelendik** 2021-06-18 07:50 UTC
Labels: bug

**Comment by okamara** [comment] 2021-06-18 10:31
Verified on dev. branch. Fixed.
